name: "Build"

on:
  push:
    branches-ignore:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ğŸ””
        uses: actions/checkout@v3

      - name: Setup Node â˜Š
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies âš™ï¸
        run: npm ci

      - name: Run type checking
        run: npm run tsc:check

      - name: Checking Code Formatting ğŸ©ğŸ‘”ğŸ‘
        id: formatter
        run: npm run format:check

      - name: Checking Code Linting ğŸ˜‡ğŸ•Šï¸
        id: linter
        run: npm run lint:check

      - name: Running tests ğŸ§ªğŸ¥¼ğŸ§‘ğŸ¾â€ğŸ”¬
        id: test-runner
        run: npm run test:coverage

      - name: Checking Project Build ğŸ§±ğŸš§ğŸ‘·ğŸ¾â€â™€ï¸ğŸ—ï¸
        id: builder
        run: npm run build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
